# Generated by Django 3.0.4 on 2020-04-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0026_auto_20200331_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='name',
            field=models.CharField(default='Result At: Wed Apr  1 22:05:59 2020', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='name',
            field=models.CharField(default='Run API Testing At: Wed Apr  1 22:05:59 2020', editable=False, max_length=255),
        ),
    ]
