# Generated by Django 3.0.4 on 2020-04-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0027_auto_20200401_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='expected_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='name',
            field=models.CharField(default='Result At: Wed Apr  1 23:33:52 2020', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='name',
            field=models.CharField(default='Run API Testing At: Wed Apr  1 23:33:52 2020', editable=False, max_length=255),
        ),
    ]
