# Generated by Django 3.0.4 on 2020-04-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0028_auto_20200401_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='name',
            field=models.CharField(default='Result At: Thu Apr  2 22:54:19 2020', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='name',
            field=models.CharField(default='Run API Testing At: Thu Apr  2 22:54:19 2020', editable=False, max_length=255),
        ),
    ]
