# Generated by Django 3.0.4 on 2020-04-05 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0029_auto_20200402_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcaseresult',
            options={'ordering': ['result']},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='testrun',
            name='caseFeature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.Feature'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='caseLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.CaseLevel'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='caseStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.TestCaseStatus'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='requestMethod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.APIMethod'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='name',
            field=models.CharField(default='Result At: Sat Apr  4 22:59:53 2020', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='name',
            field=models.CharField(default='Run API Testing At: Sat Apr  4 22:59:53 2020', editable=False, max_length=255),
        ),
    ]
