# Generated by Django 3.0.4 on 2020-04-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0030_auto_20200404_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testrun',
            old_name='caseFeature',
            new_name='feature',
        ),
        migrations.RenameField(
            model_name='testrun',
            old_name='caseLevel',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='testrun',
            old_name='requestMethod',
            new_name='request_method',
        ),
        migrations.RenameField(
            model_name='testrun',
            old_name='caseStatus',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='testresult',
            name='name',
            field=models.CharField(default='Result At: Sat Apr  4 23:01:12 2020', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='name',
            field=models.CharField(default='Run API Testing At: Sat Apr  4 23:01:12 2020', editable=False, max_length=255),
        ),
    ]
